language: java
sudo: false
script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

services:
   - mysql

before_script:
   - mysql -e 'create database nowyouknow;' -u root
   - mysql -e 'grant all on nowyouknow.* to travis;' -u root
